#!/usr/bin/env node

var PDFImage = require("pdf-image").PDFImage;

for (var i = 1099; i < 1166; i++) {
	console.log("pdf/HKMagazine_" + i +".pdf");
	var pdfImage = new PDFImage("pdf/HKMagazine_" + i +".pdf");
	pdfImage.convertPage(0).then(function (imagePath) {
		fs.existsSync("test-0.png");
	});
}